// Code generated by scripts/generate-address-configs.ps1; DO NOT EDIT.

package version

var embeddedConfigs = map[int]AddressConfig{
	11581: {Version: 11581, LoadStartHookOffset: "0x28E9190", CDPFilterHookOffset: "0x38C4350", SceneOffsets: []int{56, 1208, 8, 1160, 16, 488}},
	11633: {Version: 11633, LoadStartHookOffset: "0x28F22A0", CDPFilterHookOffset: "0x38D41E0", SceneOffsets: []int{56, 1208, 8, 1160, 16, 488}},
	13331: {Version: 13331, LoadStartHookOffset: "0x0FFC200", CDPFilterHookOffset: "0x2420100", SceneOffsets: []int{56, 1272, 8, 1224, 16, 488}},
	13341: {Version: 13341, LoadStartHookOffset: "0x10009E0", CDPFilterHookOffset: "0x242E8E0", SceneOffsets: []int{56, 1272, 8, 1224, 16, 488}},
	13487: {Version: 13487, LoadStartHookOffset: "0x0FFB600", CDPFilterHookOffset: "0x241FEB0", SceneOffsets: []int{56, 1272, 8, 1224, 16, 488}},
	13639: {Version: 13639, LoadStartHookOffset: "0x1000990", CDPFilterHookOffset: "0x2424DE0", SceneOffsets: []int{56, 1272, 8, 1224, 16, 488}},
	13655: {Version: 13655, LoadStartHookOffset: "0x100F4B0", CDPFilterHookOffset: "0x244A9E0", SceneOffsets: []int{56, 1280, 8, 1232, 16, 488}},
	13871: {Version: 13871, LoadStartHookOffset: "0x101F160", CDPFilterHookOffset: "0x246FC40", SceneOffsets: []int{56, 1360, 8, 1312, 16, 488}},
	13909: {Version: 13909, LoadStartHookOffset: "0x101F0E0", CDPFilterHookOffset: "0x246FDC0", SceneOffsets: []int{56, 1360, 8, 1312, 16, 488}},
	14161: {Version: 14161, LoadStartHookOffset: "0x10246C0", CDPFilterHookOffset: "0x24839B0", SceneOffsets: []int{56, 1360, 8, 1312, 16, 488}},
	14199: {Version: 14199, LoadStartHookOffset: "0x10246F0", CDPFilterHookOffset: "0x24839E0", SceneOffsets: []int{56, 1360, 8, 1312, 16, 488}},
	14315: {Version: 14315, LoadStartHookOffset: "0x10004C0", CDPFilterHookOffset: "0x2424B50", SceneOffsets: []int{56, 1272, 8, 1224, 16, 488}},
	16133: {Version: 16133, LoadStartHookOffset: "0x470FAD0", CDPFilterHookOffset: "0x90FC7E0", SceneOffsets: []int{56, 1360, 8, 1312, 16, 488}},
	16203: {Version: 16203, LoadStartHookOffset: "0x4710890", CDPFilterHookOffset: "0x90FD640", SceneOffsets: []int{56, 1360, 8, 1312, 16, 488}},
	16389: {Version: 16389, LoadStartHookOffset: "0x24E4830", CDPFilterHookOffset: "0x2E2A880", SceneOffsets: []int{56, 1360, 8, 1312, 16, 488}},
	16467: {Version: 16467, LoadStartHookOffset: "0x24E4FD0", CDPFilterHookOffset: "0x2E2CC90", SceneOffsets: []int{56, 1360, 8, 1312, 16, 488}},
	16771: {Version: 16771, LoadStartHookOffset: "0x24E9130", CDPFilterHookOffset: "0x2E3C470", SceneOffsets: []int{56, 1360, 8, 1312, 16, 488}},
	16815: {Version: 16815, LoadStartHookOffset: "0x2509690", CDPFilterHookOffset: "0x2E768D0", SceneOffsets: []int{56, 1416, 8, 1360, 16, 488}},
	16965: {Version: 16965, LoadStartHookOffset: "0x2570220", CDPFilterHookOffset: "0x2F844A0", SceneOffsets: []int{56, 1416, 8, 1360, 16, 488}},
	17037: {Version: 17037, LoadStartHookOffset: "0x257D0A0", CDPFilterHookOffset: "0x2FB2310", SceneOffsets: []int{56, 1408, 8, 1352, 16, 488}},
	17071: {Version: 17071, LoadStartHookOffset: "0x258F370", CDPFilterHookOffset: "0x2FD3080", SceneOffsets: []int{56, 1408, 8, 1352, 16, 488}},
	17127: {Version: 17127, LoadStartHookOffset: "0x2590910", CDPFilterHookOffset: "0x2FD4040", SceneOffsets: []int{56, 1408, 8, 1352, 16, 488}},
	18055: {Version: 18055, LoadStartHookOffset: "0x25A1040", CDPFilterHookOffset: "0x30031E0", SceneOffsets: []int{56, 1416, 8, 1352, 16, 488}},
	18151: {Version: 18151, LoadStartHookOffset: "0x25A2E20", CDPFilterHookOffset: "0x3013D20", SceneOffsets: []int{56, 1416, 8, 1352, 16, 488}},
	18787: {Version: 18787, LoadStartHookOffset: "0x25B2870", CDPFilterHookOffset: "0x3028AD0", SceneOffsets: []int{56, 1408, 8, 1344, 16, 488}},
	18891: {Version: 18891, LoadStartHookOffset: "0x25B50C0", CDPFilterHookOffset: "0x30245E0", SceneOffsets: []int{56, 1408, 8, 1344, 16, 488}},
	18955: {Version: 18955, LoadStartHookOffset: "0x25B52C0", CDPFilterHookOffset: "0x30248B0", SceneOffsets: []int{56, 1408, 8, 1344, 16, 488}},
	19027: {Version: 19027, LoadStartHookOffset: "0x25B52D0", CDPFilterHookOffset: "0x3024AD0", SceneOffsets: []int{56, 1408, 8, 1344, 16, 488}},
	19201: {Version: 19201, LoadStartHookOffset: "0x25B5DD0", CDPFilterHookOffset: "0x301B3C0", SceneOffsets: []int{56, 1376, 8, 1312, 16, 456}},
	19339: {Version: 19339, LoadStartHookOffset: "0x25B5DD0", CDPFilterHookOffset: "0x301BA00", SceneOffsets: []int{56, 1376, 8, 1312, 16, 456}},
	19459: {Version: 19459, LoadStartHookOffset: "0x25BB580", CDPFilterHookOffset: "0x3022F20", SceneOffsets: []int{56, 1376, 8, 1312, 16, 456}},
	19481: {Version: 19481, LoadStartHookOffset: "0x25BBA80", CDPFilterHookOffset: "0x3023420", SceneOffsets: []int{56, 1376, 8, 1312, 16, 456}},
	19749: {Version: 19749, LoadStartHookOffset: "0x25E77C0", CDPFilterHookOffset: "0x30ABC60", SceneOffsets: []int{64, 1408, 8, 1344, 16, 456}},
	19769: {Version: 19769, LoadStartHookOffset: "0x25E7990", CDPFilterHookOffset: "0x30AC0A0", SceneOffsets: []int{64, 1408, 8, 1344, 16, 456}},
	19823: {Version: 19823, LoadStartHookOffset: "0x25ED1C0", CDPFilterHookOffset: "0x30B3320", SceneOffsets: []int{64, 1408, 8, 1344, 16, 456}},
	19841: {Version: 19841, LoadStartHookOffset: "0x25EC000", CDPFilterHookOffset: "0x30B1B90", SceneOffsets: []int{64, 1408, 8, 1344, 16, 456}},
	19871: {Version: 19871, LoadStartHookOffset: "0x25CE150", CDPFilterHookOffset: "0x30A84E0", SceneOffsets: []int{64, 1472, 8, 1408, 16, 456}},
	19881: {Version: 19881, LoadStartHookOffset: "0x25CE150", CDPFilterHookOffset: "0x2B8B390", SceneOffsets: []int{64, 1472, 8, 1408, 16, 456}},
	19899: {Version: 19899, LoadStartHookOffset: "0x25CEF40", CDPFilterHookOffset: "0x30AA000", SceneOffsets: []int{64, 1472, 8, 1408, 16, 456}},
	19921: {Version: 19921, LoadStartHookOffset: "0x25CE330", CDPFilterHookOffset: "0x30A9550", SceneOffsets: []int{64, 1472, 8, 1408, 16, 456}},
	19977: {Version: 19977, LoadStartHookOffset: "0x25D14B0", CDPFilterHookOffset: "0x30B02B0", SceneOffsets: []int{64, 1480, 8, 1416, 16, 456}},
	20001: {Version: 20001, LoadStartHookOffset: "0x25D1520", CDPFilterHookOffset: "0x30B03A0", SceneOffsets: []int{64, 1480, 8, 1416, 16, 456}},
	20005: {Version: 20005, LoadStartHookOffset: "0x25DBBE0", CDPFilterHookOffset: "0x30C5D90", SceneOffsets: []int{64, 1480, 8, 1416, 16, 456}},
	20079: {Version: 20079, LoadStartHookOffset: "0x25DFB90", CDPFilterHookOffset: "0x30CF310", SceneOffsets: []int{64, 1480, 8, 1416, 16, 456}},
	20089: {Version: 20089, LoadStartHookOffset: "0x25E0170", CDPFilterHookOffset: "0x30CF8F0", SceneOffsets: []int{64, 1480, 8, 1416, 16, 456}},
	25268: {Version: 25268, LoadStartHookOffset: "0x2a5d090", CDPFilterHookOffset: "0x38e9100", SceneOffsets: []int{64, 1496, 8, 1432, 16, 456}},
	25297: {Version: 25297, LoadStartHookOffset: "0x2A5D800", CDPFilterHookOffset: "0x38EA370", SceneOffsets: []int{64, 1496, 8, 1432, 16, 456}},
}

// EmbeddedConfigs returns an independent copy of every supported WMPF address configuration.
func EmbeddedConfigs() map[int]AddressConfig {
	out := make(map[int]AddressConfig, len(embeddedConfigs))
	for version, config := range embeddedConfigs {
		config.SceneOffsets = append([]int(nil), config.SceneOffsets...)
		out[version] = config
	}
	return out
}
