param(
    [string]$SourceDir = (Join-Path $PSScriptRoot "..\configs\addresses"),
    [string]$Output = (Join-Path $PSScriptRoot "..\internal\version\configs_generated.go")
)

$ErrorActionPreference = "Stop"
$files = @(Get-ChildItem -LiteralPath $SourceDir -Filter "addresses.*.json" | Sort-Object Name)
if ($files.Count -eq 0) {
    throw "no address configs found in $SourceDir"
}

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine("// Code generated by scripts/generate-address-configs.ps1; DO NOT EDIT.")
[void]$builder.AppendLine()
[void]$builder.AppendLine("package version")
[void]$builder.AppendLine()
[void]$builder.AppendLine("var embeddedConfigs = map[int]AddressConfig{")
foreach ($file in $files) {
    $config = Get-Content -LiteralPath $file.FullName -Raw | ConvertFrom-Json
    $version = [int]$config.Version
    $expected = [int]([regex]::Match($file.Name, '^addresses\.(\d+)\.json$').Groups[1].Value)
    if ($version -ne $expected -or @($config.SceneOffsets).Count -ne 6) {
        throw "invalid address config: $($file.FullName)"
    }
    $loadStart = ([string]$config.LoadStartHookOffset).Replace('"', '\"')
    $cdpFilter = ([string]$config.CDPFilterHookOffset).Replace('"', '\"')
    $scenes = (@($config.SceneOffsets) | ForEach-Object { [int]$_ }) -join ", "
    [void]$builder.AppendLine("`t$version`: {Version: $version, LoadStartHookOffset: `"$loadStart`", CDPFilterHookOffset: `"$cdpFilter`", SceneOffsets: []int{$scenes}},")
}
[void]$builder.AppendLine("}")
[void]$builder.AppendLine()
[void]$builder.AppendLine("// EmbeddedConfigs returns an independent copy of every supported WMPF address configuration.")
[void]$builder.AppendLine("func EmbeddedConfigs() map[int]AddressConfig {")
[void]$builder.AppendLine("`tout := make(map[int]AddressConfig, len(embeddedConfigs))")
[void]$builder.AppendLine("`tfor version, config := range embeddedConfigs {")
[void]$builder.AppendLine("`t`tconfig.SceneOffsets = append([]int(nil), config.SceneOffsets...)")
[void]$builder.AppendLine("`t`tout[version] = config")
[void]$builder.AppendLine("`t}")
[void]$builder.AppendLine("`treturn out")
[void]$builder.AppendLine("}")

[System.IO.File]::WriteAllText($Output, $builder.ToString(), [System.Text.UTF8Encoding]::new($false))
& gofmt -w $Output
if ($LASTEXITCODE -ne 0) {
    throw "gofmt failed with exit code $LASTEXITCODE"
}
